export const INITIAL_SETUP = 'game/INITIAL_SETUP';
export const SET_IS_READY = 'game/SET_IS_READY';
export const SET_TEAM_GUESSING = 'game/SET_TEAM_GUESSING'
export const SET_ROUND = 'game/SET_ROUND'
export const SET_TIME_LEFT = 'game/SET_TIME_LEFT'
export const SET_CHARACTER_TO_GUESS = 'game/SET_CHARACTER_TO_GUESS'
export const ADD_POINTS = 'game/ADD_POINTS' as const
export const CHARACTER_GUESSED = 'game/CHARACTER_GUESSED'
export const SET_CHARACTERS_LEFT_TO_GUESS = 'game/SET_CHARACTERS_LEFT_TO_GUESS'
export const TICK = 'game/TICK'